version: "3"

services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: muzzSecure
      MYSQL_DATABASE: muzz
      MYSQL_USER: muzzUser
      MYSQL_PASSWORD: muzzUserPass
    ports:
      - "3306:3306"